---
name: "ID Token Exchange with GCP"

on:
  workflow_dispatch:
    inputs:
      project_number:
        description: "GCP Projekt Nummer, des Workload Identity Providers"
        required: true
        type: string
      wif_pool_name:
        description: "Name des Workload Identity Pools"
        required: false
        default: "github"
        type: string
      wif_provider:
        description: "Name des Workload Identity Providers"
        required: false
        default: "repo-id-tokens"
        type: string

jobs:
  main:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_NUMBER: "${{ inputs.project_number }}"
      WIF_POOL_NAME: "${{ inputs.wif_pool_name }}"
      WIF_PROVIDER: "${{ inputs.wif_provider }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Get ID Token for this Workflow
        env:
          ANNOTATION_TITLE: "Workflow_ID_Token"
        run: |
          id_token="$(
            curl -sS \
              -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=lab-sample-token" \
            | jq -r '.value' | base64 -w 0
          )"
          echo "::notice title=${ANNOTATION_TITLE}::${id_token}"

      - name: Authenticate to Google Cloud with ID Token
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL_NAME }}/providers/${{ env.WIF_PROVIDER }}"

      - name: Set Project for all gcloud commands
        id: project
        run: |
          project_id="$(gcloud projects describe ${PROJECT_NUMBER} --format json | jq -r '.projectId')"
          gcloud config set project "${project_id}"
          echo "id=${project_id}" >> "$GITHUB_OUTPUT"

      - name: List all Buckets
        id: buckets
        run: |
          # Get bucket names as a JSON array of strings
          buckets="$(gcloud storage buckets list --format json | jq -c '[.[].name]')"
          if [ "$(echo "$buckets" | jq 'length')" -eq 0 ]; then
            echo "::notice title=GCP_Buckets::No buckets could be retrieved. Please check the 'List all Buckets' step for further details, e.g. permission issues."
          else
            echo "::notice title=GCP_Buckets::${buckets}"
          fi
          echo "all=${buckets}" >> "$GITHUB_OUTPUT"

      - name: List files of first bucket
        env:
          BUCKETS: "${{ steps.buckets.outputs.all }}"
        run: |
          bucket=$(echo "$BUCKETS" | jq -r '.[0]')
          if [ -z "$bucket" ] || [ "$bucket" == "null" ]; then
            echo "No bucket found in the configured project."
            exit 1
          fi
          files="$(gcloud storage objects list "gs://$bucket" --format json | jq -c '[.[].name]')"
          if [ "$(echo "$files" | jq 'length')" -eq 0 ]; then
            echo "::notice title=Files_in_${bucket}::No files could be retrieved from Bucket ${bucket}. Please check the 'List files of first bucket' step for further details, e.g. permission issues."
          else
            echo "::notice title=Files_in_${bucket}::${files}"
          fi
