---
- name: Ensure lab users exist with password same as username
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ item | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
  loop: "{{ lab_users }}"

- name: Configure passwordless sudo for docker exec for lab users
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/lab-{{ item }}"
    content: |
      # Allow user to exec into their lab container without password
      {{ item }} ALL=(root) NOPASSWD: /usr/bin/docker exec -it lab-{{ item }} /bin/bash
    owner: root
    group: root
    mode: "0440"
  loop: "{{ lab_users }}"
