---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Stop all containers with names starting with "lab-"
  hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/settings.yaml

  vars:
    # Override with "-e delete_containers=true" to destroy all lab containers.
    delete_containers: false
    lab_users: "{{ lab_users | default([], true) }}"

  tasks:
    - name: Get all Docker container names (including stopped)
      ansible.builtin.shell: !unsafe "docker ps -a --format '{{.Names}}'"
      changed_when: false
      register: all_container_names

    - name: Filter container names starting with "lab-"
      set_fact:
        container_names: "{{ all_container_names.stdout_lines | select('match', '^lab-') | list }}"

    - name: Stop Lab Containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: "{{ 'absent' if delete_containers | bool else 'stopped' }}"
        force_kill: true
      loop: "{{ container_names }}"

    - name: Block SSH access for users
      ansible.builtin.include_role:
        name: sshd-lab-users
      vars:
        sshd_lab_users: "{{ lab_users }}"
