---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Stop all containers with names starting with "lab-"
  hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/settings.yaml

  pre_tasks:
    - name: Set default for lab_users if not defined
      set_fact:
        lab_users: []
      when: lab_users is not defined

  tasks:
    - name: Get list of containers for each lab user
      community.docker.docker_container_info:
        name: "lab-{{ item }}-*"
      loop: "{{ lab_users }}"
      register: container_info

    - name: Combine all container names into one list
      set_fact:
        container_names: >-
          {{
          container_info.results
          | map(attribute='containers')
          | flatten
          | map(attribute='Name')
          | list
          }}

    - name: Stop Lab Containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ container_names }}"

    - name: Block SSH access for users
      ansible.builtin.include_role:
        name: sshd-user-no-lab
      vars:
        sshd_no_lab_users: "{{ lab_users }}"
