- name: Configure sshd for each sshd_lab_user
  include_tasks: user.yml
  # Combine both variables into a unique list to support single and multiple user configurations
  loop: "{{ ([sshd_lab_users | default([], true)] + [sshd_lab_user | default([], true)]) | flatten | unique }}"
  loop_control:
    loop_var: user
  register: user_config_results
