name: Test Docker Builds on Labs and Demos Changes

on:
  push:
    paths:
      - "labs/**"
      - "demos/**"
  pull_request:
    paths:
      - "labs/**"
      - "demos/**"

jobs:
  changed_files:
    runs-on: ubuntu-24.04
    name: Test changed-files
    outputs:
      matrix: ${{ steps.changed-labs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true

      - name: Find changed labs and demos directories
        id: changed-labs
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        run: |
          # Parse the JSON array of changed files, truncate each path to two levels, deduplicate, and output as compact JSON.
          result="$(
            jq -c \
            '[.[] | split("/") | select(length >= 2) | .[0:2] | join("/")] | unique' \
            <<< "$ALL_CHANGED_FILES"
          )"
          echo "matrix=$result" >> $GITHUB_OUTPUT

  build-docker-images:
    needs: changed_files
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{ fromJson(needs.changed_files.outputs.matrix) }}
      fail-fast: false
    steps:
      # Checkout the repository
      - name: Build Docker Image
        uses: docker/build-push-action@v6.18.0
        with:
          push: false
          context: ./${{ matrix }}
          file: ./${{ matrix }}/Dockerfile
          tags: test:latest
